import type { Metadata } from "next";
import { Syne, Epilogue } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  weight: ["400", "500", "600", "700", "800"],
});

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${epilogue.variable}`}>
        {children}
      </body>
    </html>
  );
}
